### ISSUE TITLE
Error when install in ubuntu server 22.04

### ISSUE THREAD

**Issue by voquocduy** [ssjsk/bitnami-postgres-ha-helm-kubernetes#1]
Can you help me install your postgres-ha in ubuntu server 22.04
this is error:

root@k8s-master:/opt# kubectl describe pods my-pg-cluster1-postgresql-ha-postgresql-0 --namespace postgres-cluster
Name:             my-pg-cluster1-postgresql-ha-postgresql-0
Namespace:        postgres-cluster
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app.kubernetes.io/component=postgresql
                  app.kubernetes.io/instance=my-pg-cluster1
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=postgresql-ha
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=my-pg-cluster1-postgresql-ha-postgresql-78574f8888
                  helm.sh/chart=postgresql-ha-11.7.7
                  role=data
                  statefulset.kubernetes.io/pod-name=my-pg-cluster1-postgresql-ha-postgresql-0
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/my-pg-cluster1-postgresql-ha-postgresql
Init Containers:
  init-chmod-data:
    Image:      docker.io/bitnami/bitnami-shell:11-debian-11-r130
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      mkdir -p /bitnami/postgresql/conf /bitnami/postgresql/data /bitnami/postgresql/lock
      chmod 700 /bitnami/postgresql/conf /bitnami/postgresql/data /bitnami/postgresql/lock
      chown 1001:1001 /bitnami/postgresql
      find /bitnami/postgresql -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
        xargs -r chown -R 1001:1001

    Environment:  <none>
    Mounts:
      /bitnami/postgresql from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6x4tt (ro)
Containers:
  postgresql:
    Image:      docker.io/bitnami/postgresql-repmgr:15.3.0-debian-11-r16
    Port:       5432/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      1
      memory:   1Gi
    Liveness:   exec [bash -ec PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "admin" -d "thingsboard" -h 127.0.0.1 -p 5432 -c "SELECT 1"] delay=5s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [bash -ec PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "admin" -d "thingsboard" -h 127.0.0.1 -p 5432 -c "SELECT 1"] delay=5s timeout=5s period=10s #success=1 #failure=6
    Startup:    exec [bash -ec PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "admin" -d "thingsboard" -h 127.0.0.1 -p 5432 -c "SELECT 1"] delay=5s timeout=5s period=10s #success=1 #failure=10
    Environment:
      BITNAMI_DEBUG:                           true
      POSTGRESQL_VOLUME_DIR:                   /bitnami/postgresql
      PGDATA:                                  /bitnami/postgresql/data
      POSTGRES_USER:                           admin
      POSTGRES_PASSWORD:                       <set to the key 'password' in secret 'my-pg-cluster1-postgresql-ha-postgresql'>  Optional: false
      POSTGRES_DB:                             thingsboard
      POSTGRESQL_LOG_HOSTNAME:                 true
      POSTGRESQL_LOG_CONNECTIONS:              false
      POSTGRESQL_LOG_DISCONNECTIONS:           false
      POSTGRESQL_PGAUDIT_LOG:                  ROLE, MISC_SET
      POSTGRESQL_PGAUDIT_LOG_CATALOG:          true
      POSTGRESQL_CLIENT_MIN_MESSAGES:          error
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:     pgaudit, repmgr
      POSTGRESQL_MAX_CONNECTIONS:              100
      REPMGR_USE_PGREWIND:                     true
      POSTGRESQL_POSTGRES_CONNECTION_LIMIT:    10
      POSTGRESQL_USERNAME_CONNECTION_LIMIT:    100
      POSTGRESQL_ENABLE_TLS:                   no
      POSTGRESQL_PORT_NUMBER:                  5432
      REPMGR_PORT_NUMBER:                      5432
      REPMGR_PRIMARY_PORT:                     5432
      MY_POD_NAME:                             my-pg-cluster1-postgresql-ha-postgresql-0 (v1:metadata.name)
      REPMGR_UPGRADE_EXTENSION:                no
      REPMGR_PGHBA_TRUST_ALL:                  no
      REPMGR_MOUNTED_CONF_DIR:                 /bitnami/repmgr/conf
      REPMGR_NAMESPACE:                        postgres-cluster (v1:metadata.namespace)
      REPMGR_PARTNER_NODES:                    my-pg-cluster1-postgresql-ha-postgresql-0.my-pg-cluster1-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,my-pg-cluster1-postgresql-ha-postgresql-1.my-pg-cluster1-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,my-pg-cluster1-postgresql-ha-postgresql-2.my-pg-cluster1-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,
      REPMGR_PRIMARY_HOST:                     my-pg-cluster1-postgresql-ha-postgresql-0.my-pg-cluster1-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local
      REPMGR_NODE_NAME:                        $(MY_POD_NAME)
      REPMGR_NODE_NETWORK_NAME:                $(MY_POD_NAME).my-pg-cluster1-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local
      REPMGR_NODE_TYPE:                        data
      REPMGR_LOG_LEVEL:                        NOTICE
      REPMGR_CONNECT_TIMEOUT:                  5
      REPMGR_RECONNECT_ATTEMPTS:               2
      REPMGR_RECONNECT_INTERVAL:               3
      REPMGR_USERNAME:                         admin
      REPMGR_PASSWORD:                         <set to the key 'repmgr-password' in secret 'my-pg-cluster1-postgresql-ha-postgresql'>  Optional: false
      REPMGR_DATABASE:                         repmgr
      REPMGR_FENCE_OLD_PRIMARY:                no
      REPMGR_CHILD_NODES_CHECK_INTERVAL:       5
      REPMGR_CHILD_NODES_CONNECTED_MIN_COUNT:  1
      REPMGR_CHILD_NODES_DISCONNECT_TIMEOUT:   30
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:     2
      POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE:    ANY
    Mounts:
      /bitnami/postgresql from data (rw)
      /bitnami/postgresql/conf/conf.d/ from postgresql-extended-config (rw)
      /pre-stop.sh from hooks-scripts (rw,path="pre-stop.sh")
      /readiness-probe.sh from hooks-scripts (rw,path="readiness-probe.sh")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6x4tt (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-my-pg-cluster1-postgresql-ha-postgresql-0
    ReadOnly:   false
  hooks-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-pg-cluster1-postgresql-ha-postgresql-hooks-scripts
    Optional:  false
  postgresql-extended-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-pg-cluster1-postgresql-ha-postgresql-extended-configuration
    Optional:  false
  kube-api-access-6x4tt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  20m                default-scheduler  0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
  Warning  FailedScheduling  15m (x5 over 20m)  default-scheduler  0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..

**Comment by ssjsk** [comment]
hi @voquocduy : can you confirm persistent volume settings that you're using in your helm chart? Have you pre-created the PVCs? Additionally, do you've K8 cluster up and running to support required number of CPUs/Memory based on your helm chart?
If you're running low on K8 resources, I suggest you reduce CPU/Memory in helm chart values.yaml

**Comment by voquocduy** [comment]
Thank you for your reply.
This is my pv.yaml file

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-volume-0
  labels:
    type: local
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres/data"

I use VituralBox 
![image](https://github.com/ssjsk/bitnami-postgres-ha-helm-kubernetes/assets/91975892/92c9e62a-48b0-455b-b7ae-6c113fc4c3db)
1 master and 1 node (same config, you can see in the picture)
I use MACBOOK PRO RETINA 2015, core i7 ram 16GB 

** sorry removing your phone number **

**Comment by ssjsk** [comment]
Hi @voquocduy 
For PVC name,  there's convention in case of  this HA setup. name  should be  data-{YOUR_CLUSTER_NAME}-postgresql-ha-postgresql-0, which in your case should be  data-my-pg-cluster1-postgresql-ha-postgresql-0 for PVC that will be bound to 0 i.e. primary node, similarly  data-my-pg-cluster1-postgresql-ha-postgresql-1 for binding to 1st replica,  data-my-pg-cluster1-postgresql-ha-postgresql-2 for 2nd replica and so on, minimum replicas recommended is 3 but in your case its 1 plus 1 pg-pool. 
Also you've to disable volume persistence 
```
volumePermissions:
  ## @param volumePermissions.enabled Enable init container to adapt volume permissions
  ##
  enabled: false
```

let me know if this works.

**Comment by voquocduy** [comment]
Thank you, I removed volumePermissions, change replicas  to 3

duyvq@k8s-master:/opt$ kubectl describe pod my-pg-cluster-postgresql-ha-postgresql-2 --namespace postgres-cluster
Name:             my-pg-cluster-postgresql-ha-postgresql-2
Namespace:        postgres-cluster
Priority:         0
Service Account:  default
Node:             k8s-node1/
Start Time:       Tue, 05 Dec 2023 04:41:59 +0000
Labels:           app.kubernetes.io/component=postgresql
                  app.kubernetes.io/instance=my-pg-cluster
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=postgresql-ha
                  apps.kubernetes.io/pod-index=2
                  controller-revision-hash=my-pg-cluster-postgresql-ha-postgresql-775c988c9
                  helm.sh/chart=postgresql-ha-11.7.7
                  role=data
                  statefulset.kubernetes.io/pod-name=my-pg-cluster-postgresql-ha-postgresql-2
Annotations:      cni.projectcalico.org/containerID: eb56d82d4c0745922112e5c7d55f6bf8a8ab8de3b3bc446ffb52634c61eb26b7
                  cni.projectcalico.org/podIP: 192.168.36.69/32
                  cni.projectcalico.org/podIPs: 192.168.36.69/32
Status:           Running
IP:               192.168.36.69
IPs:
  IP:           192.168.36.69
Controlled By:  StatefulSet/my-pg-cluster-postgresql-ha-postgresql
Containers:
  postgresql:
    Container ID:   cri-o://2502bdc98503ef18f66a1bd4861b9562e96662d7699c2c012402f11972b43454
    Image:          docker.io/bitnami/postgresql-repmgr:15.3.0-debian-11-r16
    Image ID:       7363251bb06d919cbabfd735b559e886a36c92da7f95d2ab27a7084f6f538d48
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 05 Dec 2023 04:42:42 +0000
      Finished:     Tue, 05 Dec 2023 04:43:23 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 05 Dec 2023 04:42:01 +0000
      Finished:     Tue, 05 Dec 2023 04:42:41 +0000
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     1
      memory:  256Mi
    Requests:
      cpu:      1
      memory:   256Mi
    Liveness:   exec [bash -ec PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "postgres" -d "postgres" -h 127.0.0.1 -p 5432 -c                                     "SELECT 1"] delay=5s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [bash -ec PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "postgres" -d "postgres" -h 127.0.0.1 -p 5432 -c                                     "SELECT 1"] delay=5s timeout=5s period=10s #success=1 #failure=6
    Startup:    exec [bash -ec PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "postgres" -d "postgres" -h 127.0.0.1 -p 5432 -c                                     "SELECT 1"] delay=5s timeout=5s period=10s #success=1 #failure=10
    Environment:
      BITNAMI_DEBUG:                           true
      POSTGRESQL_VOLUME_DIR:                   /bitnami/postgresql
      PGDATA:                                  /bitnami/postgresql/data
      POSTGRES_USER:                           postgres
      POSTGRES_PASSWORD:                       <set to the key 'password' in secret 'my-pg-cluster-postgresql-ha-postgres                                    ql'>  Optional: false
      POSTGRES_DB:                             postgres
      POSTGRESQL_LOG_HOSTNAME:                 true
      POSTGRESQL_LOG_CONNECTIONS:              false
      POSTGRESQL_LOG_DISCONNECTIONS:           false
      POSTGRESQL_PGAUDIT_LOG:                  ROLE, MISC_SET
      POSTGRESQL_PGAUDIT_LOG_CATALOG:          true
      POSTGRESQL_CLIENT_MIN_MESSAGES:          error
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:     pgaudit, repmgr
      POSTGRESQL_MAX_CONNECTIONS:              100
      REPMGR_USE_PGREWIND:                     true
      POSTGRESQL_POSTGRES_CONNECTION_LIMIT:    10
      POSTGRESQL_USERNAME_CONNECTION_LIMIT:    100
      POSTGRESQL_ENABLE_TLS:                   no
      POSTGRESQL_PORT_NUMBER:                  5432
      REPMGR_PORT_NUMBER:                      5432
      REPMGR_PRIMARY_PORT:                     5432
      MY_POD_NAME:                             my-pg-cluster-postgresql-ha-postgresql-2 (v1:metadata.name)
      REPMGR_UPGRADE_EXTENSION:                no
      REPMGR_PGHBA_TRUST_ALL:                  no
      REPMGR_MOUNTED_CONF_DIR:                 /bitnami/repmgr/conf
      REPMGR_NAMESPACE:                        postgres-cluster (v1:metadata.namespace)
      REPMGR_PARTNER_NODES:                    my-pg-cluster-postgresql-ha-postgresql-0.my-pg-cluster-postgresql-ha-postg                                    resql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,my-pg-cluster-postgresql-ha-postgresql-1.my-pg-cluster-postgresql-ha                                    -postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,my-pg-cluster-postgresql-ha-postgresql-2.my-pg-cluster-postgre                                    sql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,
      REPMGR_PRIMARY_HOST:                     my-pg-cluster-postgresql-ha-postgresql-0.my-pg-cluster-postgresql-ha-postg                                    resql-headless.$(REPMGR_NAMESPACE).svc.cluster.local
      REPMGR_NODE_NAME:                        $(MY_POD_NAME)
      REPMGR_NODE_NETWORK_NAME:                $(MY_POD_NAME).my-pg-cluster-postgresql-ha-postgresql-headless.$(REPMGR_NA                                    MESPACE).svc.cluster.local
      REPMGR_NODE_TYPE:                        data
      REPMGR_LOG_LEVEL:                        NOTICE
      REPMGR_CONNECT_TIMEOUT:                  5
      REPMGR_RECONNECT_ATTEMPTS:               2
      REPMGR_RECONNECT_INTERVAL:               3
      REPMGR_USERNAME:                         repmgr
      REPMGR_PASSWORD:                         <set to the key 'repmgr-password' in secret 'my-pg-cluster-postgresql-ha-p                                    ostgresql'>  Optional: false
      REPMGR_DATABASE:                         repmgr
      REPMGR_FENCE_OLD_PRIMARY:                no
      REPMGR_CHILD_NODES_CHECK_INTERVAL:       5
      REPMGR_CHILD_NODES_CONNECTED_MIN_COUNT:  1
      REPMGR_CHILD_NODES_DISCONNECT_TIMEOUT:   30
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:     2
      POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE:    ANY
    Mounts:
      /bitnami/postgresql from data (rw)
      /bitnami/postgresql/conf/conf.d/ from postgresql-extended-config (rw)
      /pre-stop.sh from hooks-scripts (rw,path="pre-stop.sh")
      /readiness-probe.sh from hooks-scripts (rw,path="readiness-probe.sh")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2mp7k (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-my-pg-cluster-postgresql-ha-postgresql-2
    ReadOnly:   false
  hooks-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-pg-cluster-postgresql-ha-postgresql-hooks-scripts
    Optional:  false
  postgresql-extended-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      my-pg-cluster-postgresql-ha-postgresql-extended-configuration
    Optional:  false
  kube-api-access-2mp7k:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  88s                default-scheduler  0/3 nodes are available: pod has unbound immediate Per                                    sistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
  Normal   Scheduled         87s                default-scheduler  Successfully assigned postgres-cluster/my-pg-cluster-p                                    ostgresql-ha-postgresql-2 to k8s-node1
  Normal   Pulled            44s (x2 over 86s)  kubelet            Container image "docker.io/bitnami/postgresql-repmgr:1                                    5.3.0-debian-11-r16" already present on machine
  Normal   Created           44s (x2 over 85s)  kubelet            Created container postgresql
  Normal   Started           44s (x2 over 85s)  kubelet            Started container postgresql
  Warning  Unhealthy         6s (x8 over 76s)   kubelet            Startup probe failed: psql: error: connection to serve                                    r at "127.0.0.1", port 5432 failed: Connection refused
           Is the server running on that host and accepting TCP/IP connections?
  Warning  BackOff  3s  kubelet  Back-off restarting failed container postgresql in pod my-pg-cluster-postgresql-ha-postg                                    resql-2_postgres-cluster(b926dc38-5fbd-43bc-bdbd-793d4826f0b4)

Please help me see it. If you have time, please contact me via email: quocduypt95@gmail.com, I will ask for your help and pay you the fee
